apiVersion: apps/v1
kind: Deployment
metadata:
  name: smeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smeapp
  template:
    metadata:
      labels:
        app: smeapp
    spec:
      containers:
      - name: smeapp-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$GCLOUD_PROJECT/smeapp:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
